###
GET http://localhost:8080/api/stocks
Accept: application/json

###
GET http://localhost:8080/api/stocks/11
Accept: application/json

###
POST http://localhost:8080/api/stocks
Content-Type: application/json

{
  "name": "Waters",
  "currentPrice": 2.0
}

###
PUT  http://localhost:8080/api/stocks
Content-Type: application/json

{
  "currentPrice": 11.0,
  "id": 11
}


